fix issus#2040
alibaba/spring-cloud-alibaba pull request #2041
Opened 2021-04-15 05:41 UTC by pomeloHu

### Describe what this PR does / why we need it
修复自定义bean无法被rockmq启用的bug

### Does this pull request fix one issue?

Fixes #2040

### Describe how you did it
把RocketMQConfigBeanPostProcessor的注入方式从spring.binders移动到spring.factories中，
前者经过spring-cloud-stream代理会出现一个新的child context 导致自定义常用bean无法经过RocketMQConfigBeanPostProcessor处理

### Describe how to verify it
启动RocketMQProduceApplication事务消息通过TransactionListenerImpl且无错误

### Special notes for reviews

2021-04-15 05:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=2041) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=2041) before we can accept your contribution.<br/><hr/>**Spike** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/spring-cloud-alibaba?pullRequest=2041) it.</sub>

2021-04-27 08:35 UTC, zkzlx requested changes

2021-04-30 02:11 UTC, pomeloHu commented on spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/resources/META-INF/spring.factories
> +com.alibaba.cloud.stream.binder.rocketmq.custom.RocketMQConfigBeanPostProcessor
OK，之前是看类名看起来是专供我就没放进去。CompositeMessageConverter也移动过去了

2021-04-30 02:52 UTC, zkzlx commented
LGTM

2021-05-17 03:32 UTC, merged

2021-05-24 06:23 UTC, pomeloHu commented
我把CompositeMessageConverter的注入移动到ExtendedBindingHandlerMappingsProviderConfiguration之后产生了新的问题
我先说下问题如下：
我是自定义了一个MessageConverter的 按照spring-cloud-stream的设计 我只要将我自定义的bean注入到spring中
```
	@Bean
	public MappingHessianConverter mappingHessianConverter() {
		return new MappingHessianConverter();
	}
```
stream会优先使用我自定义的MessageConverter，

但是spring-cloud-stream-rocketmq也注入了一个自定义MessageConverter，就是这个RocketMQMessageConverter
```
	@Bean(RocketMQMessageConverter.DEFAULT_NAME)
	@ConditionalOnMissingBean(name = { RocketMQMessageConverter.DEFAULT_NAME })
	public CompositeMessageConverter rocketMQMessageConverter() {
		return new RocketMQMessageConverter().getMessageConverter();
	}
```
然后因为注入顺序的缘故，RocketMQMessageConverter排在了我写的MappingHessianConverter前面，使我的Converter未被使用/无效
![image](https://user-images.githubusercontent.com/26758630/119303259-08958680-bc98-11eb-9b72-38a60924b049.png)
-------问题描述结束---------

-------个人看法---------
大致看了下stream-rocketmq的源码，说下我的看法：
1.按照stream-rocketmq的逻辑，我可以在我自定义MessageConverter注入的是制定bean name='rocketMQMessageConverter'，但这样会破坏stream原有的设计。（这是顺着现有代码去修正的方案）（方案一，不推荐）

2.CompositeMessageConverter的用处有二，一是上面说的注入到spring容器中；二是rocketmq接收到stream传递消息的时候，对接收到的消息做一次转换，这里是stream-rocketmq的设计（RocketMQProducerMessageHandler#handleMessageInternal、RocketMQMessageConverterSupport#convertMessage2MQ）。这里我认为它的实际用处其实只有二，一可以不做，所以这里可以直接去掉注入。（方案二）

3.据我所知，RocketMQMessageConverter这个东西就是为了在RocketMQMessageConverterSupport#convertMessage2MQ中将stream传古来的payload转换成byte数组，但其实spring已经管理好了一份CompositeMessageConverter在SimpleFunctionRegistry中，我们使用直接取用就好了，它已经提供了一份默认的实现，在stream-rocketmq中无需再定义一份。甚至 都不需要做一次doConvert（我是指payload从obj转换成byte[]的过程），因为在stream发送给具体实现之前，它已经将payload转成了byte[]。（方案三）
-------看法描述结束---------

我也是今天重新测试的发现这个问题，之前MessageConverter都是生效的（我修改之前）

我看到的可能会有片面性，我没有完整的系统的看过你们的实现，如有不对请指正
@zkzlx