fix: Update copyright year
alibaba/spring-cloud-alibaba pull request #3096
Opened 2023-01-13 09:54 UTC by 123liuziming

Update copyright year in governance related module

2023-01-14 07:05 UTC, ruansheng8 approved these changes

2023-01-16 02:02 UTC, ralf0131 requested changes

2023-01-16 02:02 UTC, ralf0131 commented on spring-cloud-alibaba-starters/spring-cloud-alibaba-commons/src/main/java/com/alibaba/cloud/commons/governance/auth/condition/AuthCondition.java
> + * Copyright 2022-2023 the original author or authors.
The initial year should be kept, in this case 2013-2023

2023-01-16 02:04 UTC, ralf0131 commented on spring-cloud-alibaba-starters/spring-cloud-alibaba-commons/src/main/java/com/alibaba/cloud/commons/governance/auth/condition/AuthCondition.java
> + * Copyright 2022-2023 the original author or authors.
Ah, I found that I was misunderstood. Your change is correct as this is a new module.

2023-01-16 02:41 UTC, ralf0131 approved these changes
LGTM

2023-01-16 02:49 UTC, ralf0131 commented
BTW you do not finish all the changes. There are still other source files which need to be updated. Anyway I will merge this pull request.

2023-01-16 02:49 UTC, merged