fallback support factoryBean
alibaba/spring-cloud-alibaba pull request #3135
Opened 2023-02-03 05:26 UTC by min1854

### Describe what this PR does / why we need it
fallback support factoryBean

### Does this pull request fix one issue?

https://github.com/spring-cloud/spring-cloud-openfeign/issues/822

### Describe how you did it

### Describe how to verify it
junit test

### Special notes for reviews

2023-02-03 05:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=3135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=3135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/spring-cloud-alibaba?pullRequest=3135) it.</sub>

2023-02-04 03:18 UTC, min1854 commented
I can build normally locally

2023-02-04 07:57 UTC, min1854 commented
I didn't understand the issue, I run it locally as normal

2023-02-05 07:28 UTC, ruansheng8 requested changes

2023-02-05 07:28 UTC, ruansheng8 commented on spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/FallbackSupportFactoryBeanTests.java
> +public class FallbackSupportFactoryBeanTests {
The class name should start with `Sentinel` , For example, `SentinelFallbackSupportFactoryBeanTests`

2023-02-05 07:28 UTC, ruansheng8 commented on spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeign.java
Add a comment here to explain what issue was fixed, e.g. fix #3135.

2023-02-06 03:06 UTC, ruansheng8 requested changes

2023-02-06 03:06 UTC, ruansheng8 commented on spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelFallbackSupportFactoryBeanTests.java
> +}
The `CheckStyle` plugin is temporarily unavailable on the `2022.x` branch. Please copy the PR code to the `2021.x` branch and then run `mvn clean validate` to check the code. For example, each file should end with a blank line.
See https://github.com/spring-cloud/spring-cloud-build#checkstyle

![image](https://user-images.githubusercontent.com/24709538/216874092-1658617a-c865-40f3-a9b9-4372c6f3b94d.png)

2023-02-06 03:26 UTC, ruansheng8 commented
The `CheckStyle` plugin is temporarily unavailable on the `2022.x` branch. Please copy the PR code to the `2021.x` branch and then run `mvn clean validate` to check the code. For example, each file should end with a blank line.
See https://github.com/spring-cloud/spring-cloud-build#checkstyle

![image](https://user-images.githubusercontent.com/24709538/216874092-1658617a-c865-40f3-a9b9-4372c6f3b94d.png)

2023-02-16 13:13 UTC, ruansheng8 approved these changes

2023-02-18 09:23 UTC, steverao approved these changes
Please check whether need to create a same PR to branch of 2021.x and 2.2.x. They are also main branch of community.

2023-02-18 09:23 UTC, merged

2023-02-20 06:16 UTC, min1854 commented
> Please check whether need to create a same PR to branch of 2021.x and 2.2.x. They are also main branch of community.

Does it mean me? If so, how should I do this, create two pull requests?

2023-02-20 06:50 UTC, ruansheng8 commented
> > Please check whether need to create a same PR to branch of 2021.x and 2.2.x. They are also main branch of community.
> 
> Does it mean me? If so, how should I do this, create two pull requests?

Yes , the changes in this PR are applicable to both the `2021.x` and `2.2.x` branches, please submit two separate PR to merge them into `2021.x` and `2.2.x`, respectively.