Fix configuration load error due to prefix
alibaba/spring-cloud-alibaba pull request #3562
Opened 2023-12-29 09:18 UTC by youngledo

### Describe what this PR does / why we need it
#3561 

### Does this pull request fix one issue?

### Describe how you did it
Delete the following code:
`com.alibaba.cloud.nacos.client.NacosPropertySourceLocator#locate`
<img width="863" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/5c671241-3825-4112-bb7c-a73e380aad90">
And the name field should be used here:
<img width="991" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/637aedb6-3afa-4c6a-b309-486771137d25">
Here, only the default configuration is loaded, which is `spring.cloud.nacos.configuration.name`, that is:
<img width="949" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/29128351-e6b9-4a14-993c-34cc756bd02d">

Here you can splice the prefix.
<img width="895" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/975403a5-5305-43f3-a26c-8964ae82d9f1">

### Describe how to verify it
Install to the local repository, using the repaired version:
<img width="1255" alt="image" src="https://github.com/alibaba/spring-cloud-alibaba/assets/68590897/79af49eb-834c-449f-8e12-b146dc3a9814">

2023-12-29 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=3562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=3562) before we can accept your contribution.<br/><hr/>**huangxiao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/spring-cloud-alibaba?pullRequest=3562) it.</sub>

2023-12-29 09:35 UTC, youngledo reviewed
Perfect!

2024-01-04 01:10 UTC, chickenlj commented
Duplicated with https://github.com/alibaba/spring-cloud-alibaba/pull/3563

2024-01-04 07:57 UTC, chickenlj commented
Reopen, it's for 2021.x

2024-01-04 07:58 UTC, chickenlj approved these changes
LGTM.

2024-01-15 12:04 UTC, yuluo-yx commented
pls fix ci bug @youngledo

2024-01-16 08:10 UTC, youngledo commented
> pls fix ci bug @youngledo

It seems that this submission does not involve unit testing, so I am not sure how to fix it. Is there an example?

https://private-user-images.githubusercontent.com/68590897/294425416-2b229f0b-d9ff-41c7-a058-5e9c2c0b131f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTI5MTMsIm5iZiI6MTcwNTM5MjYxMywicGF0aCI6Ii82ODU5MDg5Ny8yOTQ0MjU0MTYtMmIyMjlmMGItZDlmZi00MWM3LWEwNTgtNWU5YzJjMGIxMzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4MTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNThlMjhiYWU3ZWE5YzNhMTMwZGNhZDZmMjdiNWQzZGJkMTRiMjRkMzZkYmQ2ZDc0MTU4NzQxYWJiYzlkYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pJeHtjJStDbvxb3hUEPh1ypo5XUpW7ND5DElmer_gg

For example, this unit test obtains the value of the environment itself, while the code is a fixed "dev". How to correct it?

2024-01-17 02:19 UTC, yuluo-yx commented
> > pls fix ci bug @youngledo
> 
> It seems that this submission does not involve unit testing, so I am not sure how to fix it. Is there an example?
> 
> ![image](https://private-user-images.githubusercontent.com/68590897/296976631-a6928147-b6ad-4e25-8054-6b63c9c7743a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTgyMDEsIm5iZiI6MTcwNTQ1NzkwMSwicGF0aCI6Ii82ODU5MDg5Ny8yOTY5NzY2MzEtYTY5MjgxNDctYjZhZC00ZTI1LTgwNTQtNmI2M2M5Yzc3NDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YmNhMzUwMmQyZGY1MDExMjQ1ZGE3YzRlNTYwNTg5OTc2NjNkZDg3OGMwMGM2NGQ1MDgxZDdjODNjZTJlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LIkv5rISQ7cWBGsM1OB3pZhDmQcUrsDiOtrUHlR12_A) For example, this unit test obtains the value of the environment itself, while the code is a fixed "dev". How to correct it?

It doesn't seem to be your problem, pls rerun ci @ruansheng8

2024-01-30 02:42 UTC, youngledo commented
> > > pls fix ci bug @youngledo
> > 
> > 
> > It seems that this submission does not involve unit testing, so I am not sure how to fix it. Is there an example?
> > ![image](https://private-user-images.githubusercontent.com/68590897/296976631-a6928147-b6ad-4e25-8054-6b63c9c7743a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTgyMDEsIm5iZiI6MTcwNTQ1NzkwMSwicGF0aCI6Ii82ODU5MDg5Ny8yOTY5NzY2MzEtYTY5MjgxNDctYjZhZC00ZTI1LTgwNTQtNmI2M2M5Yzc3NDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YmNhMzUwMmQyZGY1MDExMjQ1ZGE3YzRlNTYwNTg5OTc2NjNkZDg3OGMwMGM2NGQ1MDgxZDdjODNjZTJlNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LIkv5rISQ7cWBGsM1OB3pZhDmQcUrsDiOtrUHlR12_A) For example, this unit test obtains the value of the environment itself, while the code is a fixed "dev". How to correct it?
> 
> It doesn't seem to be your problem, pls rerun ci @ruansheng8

There are still errors in unit testing. Is it a problem with the environment itself? What else can I do?

2024-01-30 04:01 UTC, ruansheng8 commented
@youngledo，You should configure `dataId` and `name` separately：
```yaml
spring:
  cloud:
    nacos:
      config:
        name: upgrade-java
        file-extension: properties
```

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/6bb4cf59-a42f-4ca1-b4db-acc5df20ef26)

2024-01-30 04:02 UTC, ruansheng8 requested changes
@youngledo，You should configure `dataId` and `name` separately：
```yaml
spring:
  cloud:
    nacos:
      config:
        name: upgrade-java
        file-extension: properties
```

![image](https://github.com/alibaba/spring-cloud-alibaba/assets/24709538/6bb4cf59-a42f-4ca1-b4db-acc5df20ef26)

2024-02-19 06:47 UTC, closed without merging